[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/mr-andrew-jones/browser"

[[redirects]]
  from = "/Andrew-Jones.pdf"
  to = "/assets/cv/Andrew-Jones-v14.pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200